# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'activesupport'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'rake'
gem 'bundler'
gem 'sinatra'
gem 'activerecord-reset-pk-sequence'
gem 'whenever'