# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', '>= 6.0.5.1'
gem 'activesupport'
gem 'sinatra-activerecord'
gem 'sinatra-contrib', '>= 2.2.0'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'rake'
gem 'bundler'
gem 'sinatra', '>= 2.2.0'
gem 'activerecord-reset-pk-sequence'
gem 'whenever'